repository_type: pipeline

nf_core_version: 3.3.2

lint:
  files_unchanged:
    - .prettierignore
    - .prettierignore
    - .github/CONTRIBUTING.md
    - .prettierignore
    - CODE_OF_CONDUCT.md
    - assets/nf-core-oncoclassifynf_logo_light.png
    - docs/images/nf-core-oncoclassifynf_logo_light.png
    - docs/images/nf-core-oncoclassifynf_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
  nextflow_config:
    - manifest.name
    - manifest.homePage
    - validation.help.beforeText
    - validation.help.afterText
    - validation.summary.beforeText
    - validation.summary.afterText
  nf_test_content: false
  multiqc_config:
    - report_comment
  files_exist:
    - assets/email_template.html
    - assets/sendmail_template.txt
    - assets/email_template.txt
    - CODE_OF_CONDUCT.md
    - assets/nf-core-oncoclassifynf_logo_light.png
    - docs/images/nf-core-oncoclassifynf_logo_light.png
    - docs/images/nf-core-oncoclassifynf_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - .github/workflows/nf-test.yml
    - .github/actions/get-shards/action.yml
    - .github/actions/nf-test/action.yml
    - nf-test.config
    - tests/default.nf.test
    - .github/workflows/branch.yml
    - .github/workflows/nf-test.yml
    - .github/actions/get-shards/action.yml
    - .github/actions/nf-test/action.yml
    - .github/workflows/linting_comment.yml
    - .github/workflows/linting.yml
  readme:
    - nextflow_badge
    - nfcore_template_badge

template:
  org: bag-cnag
  name: oncoclassifynf
  description: This is pipeline for annotating vcf files with OncoClassify
  author: Claire Morgan
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - github_badges
    - ci
    - nf-test
    - fastqc
    - seqera_platform
    - gpu
    - gitpod
    - codespaces
    - vscode
    - email
    - adaptivecard
    - slackreport
  is_nfcore: false
